/**
 * Run every `scripts/smoke-*.mts` against an instance in sequence, then write
 * the answers to `docs/servicenow-smoke-findings.md` — the artifact that
 * unblocks NATIVE_ENGINE_BRIEF phases 4–6.
 *
 *   pnpm --filter web smoke <instanceId>
 */
import "@/lib/config";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs";
import path from "node:path";
import { prisma } from "@/lib/db";
import { REPO_ROOT } from "@/lib/config";

const ef = promisify(execFile);

const SMOKES = [
  "smoke-scope-write.mts",
  "smoke-updateset.mts",
  "smoke-scope-restriction.mts",
  "smoke-dictionary.mts",
  "smoke-atf.mts",
  "smoke-transaction-scope.mts",
];

async function run(script: string, instanceId: string): Promise<string> {
  const scriptPath = path.join(process.cwd(), "scripts", script);
  try {
    const { stdout, stderr } = await ef(process.execPath, ["--import", "tsx", scriptPath, instanceId], {
      cwd: process.cwd(),
      timeout: 4 * 60_000,
      maxBuffer: 20 * 1024 * 1024,
      env: process.env,
    });
    return (stdout + (stderr ? `\n[stderr]\n${stderr}` : "")).trim();
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string; message?: string };
    return `[FAILED] ${err.message ?? ""}\n${err.stdout ?? ""}\n${err.stderr ?? ""}`.trim();
  }
}

async function main() {
  const id = process.argv[2];
  if (!id) throw new Error("usage: smoke <instanceId>");
  const instance = await prisma.instance.findUniqueOrThrow({ where: { id } });

  const sections: string[] = [];
  const rows: { item: string; verdict: string; finding: string }[] = [];
  for (const s of SMOKES) {
    console.log("\n" + "═".repeat(70));
    console.log("Running " + s);
    console.log("═".repeat(70));
    const out = await run(s, id);
    console.log(out);
    sections.push(`## ${s}\n\n\`\`\`\n${out}\n\`\`\`\n`);
    // parse each `=== SMOKE: … (open item #N …) ===` block
    const blocks = out.split(/=== SMOKE: /).slice(1);
    for (const b of blocks) {
      const item = b.match(/\(open item [^)]+\)/)?.[0] ?? "?";
      const verdict = b.match(/verdict\s*:\s*(\w+)/)?.[1] ?? "?";
      const finding = b.match(/finding\s*:\s*(.+)/)?.[1]?.trim() ?? "";
      rows.push({ item, verdict, finding });
    }
  }

  // cleanup sweep
  console.log("\n" + "─".repeat(70));
  console.log(await run("smoke-cleanup.mts", id));

  const summary =
    `| Open item | Verdict | Finding |\n|---|---|---|\n` +
    rows.map((r) => `| ${r.item.replace(/[()]/g, "")} | **${r.verdict}** | ${r.finding} |`).join("\n");

  const doc =
    `# ServiceNow PDI smoke findings — ${instance.name}\n\n` +
    `> Generated by \`pnpm --filter web smoke ${id}\` on ${new Date().toISOString()}.\n` +
    `> Instance: ${instance.url} · release: ${instance.releaseName ?? "(run probe-instance)"} · authMode: ${instance.authMode}\n\n` +
    `These answer the "Open items" in NATIVE_ENGINE_BRIEF.md and gate the design of phases 4–6.\n\n` +
    `## Summary\n\n${summary}\n\n---\n\n` +
    sections.join("\n");

  const outPath = path.join(REPO_ROOT, "docs", "servicenow-smoke-findings.md");
  fs.writeFileSync(outPath, doc, "utf8");
  console.log(`\n✓ wrote ${outPath}`);
  await prisma.$disconnect();
}

main().catch(async (e) => {
  console.error(e);
  await prisma.$disconnect().catch(() => {});
  process.exit(1);
});
